from src.api.schemas.attendance import (
    AttendanceLessonInfo,
    AttendanceMoveRequest,
    AttendanceMoveResponse,
    AttendanceResponse,
    AttendanceStudentEntry,
    AttendanceSummary,
    AttendanceUpdateRequest,
    AttendanceUpdateResponse,
)
from src.api.schemas.base import (
    HealthResponse,
    ISICResponse,
    ISICUpdateRequest,
    RegisterRequest,
    ScanQueryParams,
    ScanResponse,
    TokenResponse,
    UserISICUpdateRequest,
    UserResponse,
    UserUpdateRequest,
)
from src.api.schemas.enrollment import (
    EnrollmentResponse,
    EnrollStudentRequest,
    ImportError_,
    ImportResult,
)
from src.api.schemas.hardware import (
    ConfigRequestPayload,
    HardwareCommandResponse,
    HardwareDeviceDetailResponse,
    HardwareDeviceSummaryResponse,
    HardwareSnapshotResponse,
    PairingSessionResponse,
)
from src.api.schemas.ota import OtaDeployResponse, OtaFirmwareResponse
from src.api.schemas.lesson import (
    LessonResponse,
    LessonUpdateRequest,
    WeekLessonAttendanceSummary,
    WeekLessonResponse,
)
from src.api.schemas.overview import (
    OverviewResponse,
    OverviewScheduleEntry,
    OverviewStudent,
    OverviewStudentWeek,
    OverviewWeek,
)
from src.api.schemas.schedule import (
    ScheduleEntryCreate,
    ScheduleEntryResponse,
    ScheduleEntryUpdate,
)
from src.api.schemas.semester import SemesterCreate, SemesterResponse
from src.api.schemas.subject import SubjectCreate, SubjectResponse, SubjectUpdate
from src.api.schemas.week import WeekNoteUpdate, WeekResponse

__all__ = [
    "AttendanceLessonInfo",
    "AttendanceMoveRequest",
    "AttendanceMoveResponse",
    "AttendanceResponse",
    "AttendanceStudentEntry",
    "AttendanceSummary",
    "AttendanceUpdateRequest",
    "AttendanceUpdateResponse",
    "EnrollStudentRequest",
    "EnrollmentResponse",
    "ConfigRequestPayload",
    "HealthResponse",
    "HardwareCommandResponse",
    "HardwareDeviceDetailResponse",
    "HardwareDeviceSummaryResponse",
    "HardwareSnapshotResponse",
    "ISICResponse",
    "ISICUpdateRequest",
    "ImportError_",
    "ImportResult",
    "LessonResponse",
    "LessonUpdateRequest",
    "OverviewResponse",
    "OverviewScheduleEntry",
    "OverviewStudent",
    "OverviewStudentWeek",
    "OverviewWeek",
    "RegisterRequest",
    "ScanQueryParams",
    "ScanResponse",
    "ScheduleEntryCreate",
    "ScheduleEntryResponse",
    "ScheduleEntryUpdate",
    "SemesterCreate",
    "SemesterResponse",
    "SubjectCreate",
    "SubjectResponse",
    "SubjectUpdate",
    "TokenResponse",
    "OtaDeployResponse",
    "OtaFirmwareResponse",
    "PairingSessionResponse",
    "UserISICUpdateRequest",
    "UserResponse",
    "UserUpdateRequest",
    "WeekLessonAttendanceSummary",
    "WeekLessonResponse",
    "WeekNoteUpdate",
    "WeekResponse",
]
