"""add one-time and recurrence fields to schedule entries

Revision ID: ac528ce30b21
Revises: 55f73d32b341
Create Date: 2026-04-28 21:32:43.909702

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ac528ce30b21'
down_revision = '55f73d32b341'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_entries', sa.Column('is_one_time', sa.Boolean(), nullable=False, server_default="0"))
    op.add_column('schedule_entries', sa.Column('recurrence_interval', sa.Integer(), nullable=False, server_default="1"))
    op.add_column('schedule_entries', sa.Column('end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_entries', 'end_date')
    op.drop_column('schedule_entries', 'recurrence_interval')
    op.drop_column('schedule_entries', 'is_one_time')
    # ### end Alembic commands ###

