"""Initial migration: create isic_scans table

Revision ID: f2e7dd1f048d
Revises: 
Create Date: 2025-11-17 19:53:49.892035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2e7dd1f048d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('isic_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isic_identifier', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_isic_scans_id'), 'isic_scans', ['id'], unique=False)
    op.create_index(op.f('ix_isic_scans_isic_identifier'), 'isic_scans', ['isic_identifier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_isic_scans_isic_identifier'), table_name='isic_scans')
    op.drop_index(op.f('ix_isic_scans_id'), table_name='isic_scans')
    op.drop_table('isic_scans')
    # ### end Alembic commands ###

